### ISSUE TITLE
Ancor no longer available at the url written in ancor.json

### ISSUE THREAD

**Issue by vvvlll93** [LoicGrobol/decofre#13]
Hi,

I'm currently trying to launch decofre using the command "python -m doit run -f datasets/ancor/ancor.py".
I'm having errors ("not enough space on the device", "invalid argument"), and by digging i found that the url [to ancor](https://sharedocs.huma-num.fr/wl/?id=omxQyO3MkOgUgfEVwOlBygZZHYAocTDt) in ancor.json is no longer available. 

The problem is that the source is returning a status code 200, so _download.py believe that the data is download, but in fact, no data have been downloaded and no folder are created (and, i think, that's what  might cause the "invalid argument" raise when trying to access the temp folder containing the data downloaded)

I'm trying to modify the code to no longer download the data from the source provided but to instead use direct file that i've download, but maybe you should change this part or find another source.

Just wanted to let you know.

And thanks for your work, what you achieve is really impressive !

**Comment by LoicGrobol** [comment]
Hi, good catch! I have updated with a new link that I hope should fix this. Can you try with the last master?

**Comment by vvvlll93** [comment]
The new link works ! Nice fix ! But now i have another error raised by spacy (ValueError: [E866] Expected a string or 'Doc' as input, but got: <class 'list'>.) 

Do you want me to create a new issue ?

**Comment by LoicGrobol** [comment]
Yes please!
