### ISSUE TITLE
Where're your pre-trained mention detection and coreference models?

### ISSUE THREAD

**Issue by hamzaelouiaazzani** [LoicGrobol/decofre#15]
Hello Mr. Grobol,
I want to use your pretrained models coref.model and detector.model but I couldn't find them in this repository nor a link to download them. Could you please tell me how to fix this problem?
Thank you in advance,

**Comment by LoicGrobol** [comment]
Hi,

You can find them in the [release page](https://github.com/LoicGrobol/decofre/releases).
