### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by AmirDraoui** [LoicGrobol/decofre#4]
Hi,
I am trying to train a coreference model using train config :2019-01-29-sane.jsonnet and model config : default.jsonnet, but I keep getting CUDA out of memory Error. I tried reducing the batch size with but it didn't work.
Here is the log:

`  File "/decofre/lib/python3.8/site-packages/decofre/training/sequential.py", line 82, in train
    raise e`

`  File "/decofre/lib/python3.8/site-packages/decofre/training/sequential.py", line 59, in train
    antecedent_scoring.train_eval(`

 ` File "/decofre/lib/python3.8/site-packages/decofre/tasks/antecedent_scoring.py", line 63, in train_eval
    engine.run(loader, **kwargs)`

 ` File "/decofre/lib/python3.8/site-packages/decofre/runners.py", line 445, in run
    super().run(train_loader, max_epochs=max_epochs)`

  `File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 635, in run
    return self._internal_run()`

  `File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 747, in _internal_run
    self._handle_exception(e)`

  `File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 487, in _handle_exception
    raise e`

  `File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 732, in _internal_run
    hours, mins, secs = self._run_once_on_dataset()`

  `File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 476, in _run_once_on_dataset
    self._handle_exception(e)`

`  File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 487, in _handle_exception
    raise e`

 ` File "/decofre/lib/python3.8/site-packages/ignite/engine/engine.py", line 459, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)`

`  File "/decofre/lib/python3.8/site-packages/decofre/runners.py", line 460, in _train_and_store_loss
    output = self.model(inpt)`

  `File "/decofre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)`

 ` File "/decofre/lib/python3.8/site-packages/decofre/libdecofre.py", line 853, in forward
    spans = self.span_encoder(spans)`

 ` File "/decofre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)`

`  File "/decofre/lib/python3.8/site-packages/decofre/libdecofre.py", line 727, in forward
    encoded_content = self.span_encoder(encoded_tokens, span_boundaries)`

 ` File "/decofre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)`

 ` File "/decofre/lib/python3.8/site-packages/decofre/libdecofre.py", line 672, in forward
    lstm_output, (hn, cn) = self.lstm(packed)`

  `File "/decofre/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)`

 ` File "/decofre/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 561, in forward
    result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,`

`RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 7.93 GiB total capacity; 1.20 GiB already allocated; 37.56 MiB free; 1.22 GiB reserved in total by PyTorch)`

**Comment by LoicGrobol** [comment]
Well, that's weird, in this config I never got so high a memory usage. What does nvidia-smi reports for memory usage for the sanity check config?

Also what version of Pytorch are you using?

**Comment by AmirDraoui** [comment]
Pytorch version i am using 1.4.0
Memory usage for sanity check  1167MiB

nvidia-smi output for sanity check config:

`+-----------------------------------------------------------------------------+`
`| Processes:                                                       GPU Memory |     |  GPU       PID   Type   Process name                             Usage      |`
`|=============================================================================|`
`|    0    1351               C                                 /bin/python   6299MiB |`
`|    0    1109               C                             /bin/python3.8  1167MiB |`
`|    1    116                 C                                 /bin/python   6299MiB |`
`+-----------------------------------------------------------------------------+`
`Sun May 10 04:15:22 2020`
`+-----------------------------------------------------------------------------+`
`| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |`
`|-------------------------------+----------------------+----------------------+`
`| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC || Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |`
`|===============================+======================+======================|`
`|   0  GeForce GTX 107...  Off  | 00000000:09:00.0 Off |                  N/A || 33%   44C    P2    43W / 180W |   7476MiB /  8119MiB |     47%      Default |`
`+-------------------------------+----------------------+----------------------+`
`|   1  GeForce GTX 107...  Off  | 00000000:41:00.0 Off |                  N/A || 33%   38C    P8    10W / 180W |   6309MiB /  8119MiB |      0%      Default |`
`+-------------------------------+----------------------+----------------------+`

**Comment by LoicGrobol** [comment]
Oh, that is normal memory usage, I tried to make it as low as possible, but you should reserve at least something like 2.5GiB for the default models, perhaps try when that other process is not using 6.3GiB :-)
