### ISSUE TITLE
lmbd.diskError: No space left on device

### ISSUE THREAD

**Issue by Pantalaymon** [LoicGrobol/decofre#7]
After cloning the repository and running the bootstrapt script, I try to train a model with the ANCOR dataset with:
`decofre-train --config tests/sanity-check.jsonnet --model-config decofre/models/default.jsonnet --out-dir /Models/CorefModel`
from the decofre directory.
I run into this:
![image](https://user-images.githubusercontent.com/60576980/108120827-2bfdd380-70a2-11eb-8ec2-a9bfe9a77fd9.png)

I still have over 250 GB of remaining space on my HDD (the disk that contains the dataset) and 24GB  of remaining space on my SSD (the disk with  python 3.8 )

**Comment by dseddah** [comment]
hi,
what matters is the space left on /tmp

try to see if setting the  TMPDIR to somewhere with enough disk space is enough.

also you seem to have a cuda problem.


Djamé

**Comment by LoicGrobol** [comment]
Thanks for chiming in Djamé :-) I wouldn't have thought of that.

The cuda issue I think is probably because @Pantalamon does not have a GPU on their system.

**Comment by Pantalaymon** [comment]
Thanks you!

Yes indeed, I don't have a Nvidia GPU. I had tried to use Googl Colab to have access to a GPU (and more space) but they don't run Python 3.8.

I have done` export TMPDIR=mnt/d/TEMP` but I still have the same issue.  I guess I really don't have enough space.

Unrelated (or maybe it is), I mention that there appears to be a version compatibility problem with the bootstrap script for the anchor dataset. I create a new issue for this.

**Comment by dseddah** [comment]
Hi,
you should try to see where does python stores its temp variables  (not sure if you’re on windows or linux)
if you’re on windows, maybe use the env variable editor from the system and relaunch a terminal.
https://www.tutorialspoint.com/generate-temporary-files-and-directories-using-python
but if you have a regular widnows python exectuable and try to set a TEMPDIR variables under the linux subsystem it’s likely to not work.

Good luck,
Djamé

**Comment by dseddah** [comment]
by the way you meant 
export TEMPDIR=/mnt/d/TEMP
right ?
just to be sure I'll add
export TMPDIR=$TEMPDIR
export $TMP=$TEMPDIR
